# setup options
title             : Ayan Das
description       : '<b>Deep Learning</b> enthusiast; <b>Ph.D. Student</b> @ <a href="https://www.surrey.ac.uk/">University of Surrey</a>, United Kingdom'
baseurl           : /

# author info
author:
  name            : 'Ayan Das'
  email           : 'a.das@surrey.ac.uk'
  url             : https://twitter.com/dasayan05
  github          : [metadata]


# Custom vars
version           : 1.0

# Dependencies
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: false
highlighter: rouge
excerpt_separator : "\n\n"

# Google Analytics
google_analytics: UA-165733444-1

# Gems
plugins:
  - jekyll-feed
  - jekyll-jupyter-notebook
  - jekyll-seo-tag
  - jekyll-sitemap
